// Generated by js_of_ocaml 3.1.0
(function(g){"use strict";var
af=" : flags Open_text and Open_binary are not compatible",U="Sys_error",ae=224,ad="Invalid_argument",r=1024,T=57343,ac=512,ab="End_of_file",aa="Failure",R="Undefined_recursive_module",S=" : flags Open_rdonly and Open_wronly are not compatible",Q="([^/]*)",$="Stack_overflow",f=128,b="",z="^",M=" : file already exists",N=2048,O=56320,P=240,e=248,_="Not_found",L="Assert_failure",m="/",Y="Sys_blocked_io",Z="fd ",K="Out_of_memory",X="Match_failure",V="Division_by_zero",W="static/",aJ=0;function
t(){return aJ++}function
ak(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>127)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
aV(g){for(var
h=b,c=h,a,j,d=0,i=g.length;d<i;d++){a=g.charCodeAt(d);if(a<f){for(var
e=d+1;e<i&&(a=g.charCodeAt(e))<f;e++);if(e-d>ac){c.substr(0,1);h+=c;c=b;h+=g.slice(d,e)}else
c+=g.slice(d,e);if(e==i)break;d=e}if(a<N){c+=String.fromCharCode(192|a>>6);c+=String.fromCharCode(f|a&63)}else
if(a<55296||a>=T)c+=String.fromCharCode(ae|a>>12,f|a>>6&63,f|a&63);else
if(a>=56319||d+1==i||(j=g.charCodeAt(d+1))<O||j>T)c+="\xef\xbf\xbd";else{d++;a=(a<<10)+j-56613888;c+=String.fromCharCode(P|a>>18,f|a>>12&63,f|a>>6&63,f|a&63)}if(c.length>r){c.substr(0,1);h+=c;c=b}}return h+c}function
aN(c,a){if(a.repeat)return a.repeat(c);var
d=b,e=0;if(c==0)return d;for(;;){if(c&1)d+=a;c>>=1;if(c==0)return d;a+=a;e++;if(e==9)a.slice(0,1)}}function
aY(d,e,c){var
b=new
Array(c);for(var
a=0;a<c;a++)b[a]=d[e+a];return b}function
C(c,d,a){var
e=String.fromCharCode;if(d==0&&a<=4096&&a==c.length)return e.apply(null,c);var
f=b;for(;0<a;d+=r,a-=r)f+=e.apply(null,aY(c,d,Math.min(a,r)));return f}function
ai(a){if(a.t==2)a.c+=aN(a.l-a.c.length,"\0");else
a.c=C(a.c,0,a.c.length);a.t=0}function
aU(g){for(var
l=b,d=b,i,h,j,a,c=0,k=g.length;c<k;c++){h=g.charCodeAt(c);if(h<f){for(var
e=c+1;e<k&&(h=g.charCodeAt(e))<f;e++);if(e-c>ac){d.substr(0,1);l+=d;d=b;l+=g.slice(c,e)}else
d+=g.slice(c,e);if(e==k)break;c=e}a=1;if(++c<k&&((j=g.charCodeAt(c))&-64)==f){i=j+(h<<6);if(h<ae){a=i-12416;if(a<f)a=1}else{a=2;if(++c<k&&((j=g.charCodeAt(c))&-64)==f){i=j+(i<<6);if(h<P){a=i-925824;if(a<N||a>=55295&&a<57344)a=2}else{a=3;if(++c<k&&((j=g.charCodeAt(c))&-64)==f&&h<245){a=j-63447168+(i<<6);if(a<65536||a>1114111)a=3}}}}}if(a<4){c-=a;d+="\ufffd"}else
if(a>65535)d+=String.fromCharCode(55232+(a>>10),O+(a&1023));else
d+=String.fromCharCode(a);if(d.length>r){d.substr(0,1);l+=d;d=b}}return l+d}function
aT(a){switch(a.t){case
9:return a.c;default:ai(a);case
0:if(ak(a.c)){a.t=9;return a.c}a.t=8;case
8:return aU(a.c)}}function
n(c,a,b){this.t=c;this.c=a;this.l=b}n.prototype.toString=function(){return aT(this)};function
al(a){var
b=9;if(!ak(a))b=8,a=aV(a);return new
n(b,a,a.length)}function
aL(b,a){throw[0,b,a]}function
a(a){return new
n(0,a,a.length)}function
ao(c,b){aL(c,a(b))}var
d=[0];function
j(a){ao(d.Sys_error,a)}var
o=new
Array();function
aE(e){var
a=o[e];if(!a.opened)j("Cannot flush a closed channel");if(!a.buffer||a.buffer==b)return 0;if(a.fd&&d.fds[a.fd]&&d.fds[a.fd].output){var
c=d.fds[a.fd].output;switch(c.length){case
2:c(e,a.buffer);break;default:c(a.buffer)}}a.buffer=b;return 0}if(g.process&&g.process.cwd)var
s=g.process.cwd().replace(/\\/g,m);else
var
s="/static";if(s.slice(-1)!==m)s+=m;function
aD(a){a=a
instanceof
n?a.toString():a;if(a.charCodeAt(0)!=47)a=s+a;var
e=a.split(m),c=[];for(var
d=0;d<e.length;d++)switch(e[d]){case"..":if(c.length>1)c.pop();break;case".":break;case"":if(c.length==0)c.push(b);break;default:c.push(e[d]);break}c.orig=a;return c}function
aK(a){a=a
instanceof
n?a.toString():a;j(a+": No such file or directory")}function
aP(a){return new
n(4,a,a.length)}function
aj(a){ao(d.Invalid_argument,a)}function
aq(){aj("index out of bounds")}function
aR(a,b){switch(a.t&6){default:if(b>=a.c.length)return 0;case
0:return a.c.charCodeAt(b);case
4:return a.c[b]}}function
aO(b,a){if(a>>>0>=b.l)aq();return aR(b,a)}function
p(a){if(a<0)aj("String.create");return new
n(a?2:9,b,a)}function
an(a){return a.l}function
B(b){if(g.Uint8Array)var
c=new(g.Uint8Array)(b.l);else
var
c=new
Array(b.l);var
e=b.c,d=e.length,a=0;for(;a<d;a++)c[a]=e.charCodeAt(a);for(d=b.l;a<d;a++)c[a]=0;b.c=c;b.t=4;return c}function
v(d,e,b,f,c){if(c==0)return 0;if(f==0&&(c>=b.l||b.t==2&&c>=b.c.length)){b.c=d.t==4?C(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else
if(b.t==2&&f==b.c.length){b.c+=d.t==4?C(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else{if(b.t!=4)B(b);var
g=d.c,h=b.c;if(d.t==4)if(f<=e)for(var
a=0;a<c;a++)h[f+a]=g[e+a];else
for(var
a=c-1;a>=0;a--)h[f+a]=g[e+a];else{var
i=Math.min(c,g.length-e);for(var
a=0;a<i;a++)h[f+a]=g.charCodeAt(e+a);for(;a<c;a++)h[f+a]=0}}return 0}function
ag(){}function
c(a){this.data=a}c.prototype=new
ag();c.prototype.truncate=function(a){var
b=this.data;this.data=p(a|0);v(b,0,this.data,0,a)};c.prototype.length=function(){return an(this.data)};c.prototype.write=function(b,d,g,a){var
c=this.length();if(b+a>=c){var
e=p(b+a),f=this.data;this.data=e;v(f,0,this.data,0,c)}v(d,g,this.data,b,a);return 0};c.prototype.read=function(c,a,d,b){var
e=this.length();v(this.data,c,a,d,b);return 0};c.prototype.read_one=function(a){return aO(this.data,a)};c.prototype.close=function(){};c.prototype.constructor=c;function
h(b,a){this.content={};this.root=b;this.lookupFun=a}h.prototype.nm=function(a){return this.root+a};h.prototype.lookup=function(b){if(!this.content[b]&&this.lookupFun){var
d=this.lookupFun(a(this.root),a(b));if(d!=0)this.content[b]=new
c(d[1])}};h.prototype.exists=function(a){if(a==b)return 1;var
d=a+m,e=new
RegExp(z+d);for(var
c
in
this.content)if(c.match(e))return 1;this.lookup(a);return this.content[a]?1:0};h.prototype.readdir=function(d){var
g=d==b?b:d+m,h=new
RegExp(z+g+Q),e={},c=[];for(var
f
in
this.content){var
a=f.match(h);if(a&&!e[a[1]]){e[a[1]]=true;c.push(a[1])}}return c};h.prototype.is_dir=function(a){var
e=a==b?b:a+m,f=new
RegExp(z+e+Q),g=[];for(var
d
in
this.content){var
c=d.match(f);if(c)return 1}return 0};h.prototype.unlink=function(a){var
b=this.content[a]?true:false;delete
this.content[a];return b};h.prototype.open=function(a,b){if(b.rdonly&&b.wronly)j(this.nm(a)+S);if(b.text&&b.binary)j(this.nm(a)+af);this.lookup(a);if(this.content[a]){if(this.is_dir(a))j(this.nm(a)+" : is a directory");if(b.create&&b.excl)j(this.nm(a)+M);var
d=this.content[a];if(b.truncate)d.truncate();return d}else
if(b.create){this.content[a]=new
c(p(0));return this.content[a]}else
aK(this.nm(a))};h.prototype.register=function(d,b){if(this.content[d])j(this.nm(d)+M);if(b
instanceof
n)this.content[d]=new
c(b);else
if(b
instanceof
Array)this.content[d]=new
c(aP(b));else
if(b.toString){var
e=a(b.toString());this.content[d]=new
c(e)}};h.prototype.constructor=h;function
ah(a){if(a.t!=4)B(a);return a.c}function
aS(a,c,b){b&=255;if(a.t!=4){if(c==a.c.length){a.c+=String.fromCharCode(b);if(c+1==a.l)a.t=0;return 0}B(a)}a.c[c]=b;return 0}function
aQ(b,a,c){if(a>>>0>=b.l)aq();return aS(b,a,c)}var
A=g.Buffer;function
l(a){this.fs=require("fs");this.fd=a}l.prototype=new
ag();l.prototype.truncate=function(a){this.fs.ftruncateSync(this.fd,a|0)};l.prototype.length=function(){return this.fs.fstatSync(this.fd).size};l.prototype.write=function(f,b,c,e){var
a=ah(b);if(!(a
instanceof
g.Uint8Array))a=new(g.Uint8Array)(a);var
d=new
A(a);this.fs.writeSync(this.fd,d,c,e,f);return 0};l.prototype.read=function(h,d,c,f){var
a=ah(d);if(!(a
instanceof
g.Uint8Array))a=new(g.Uint8Array)(a);var
e=new
A(a);this.fs.readSync(this.fd,e,c,f,h);for(var
b=0;b<f;b++)aQ(d,c+b,e[c+b]);return 0};l.prototype.read_one=function(c){var
b=new(g.Uint8Array)(1),a=new
A(b);this.fs.readSync(this.fd,a,0,1,c);return a[0]};l.prototype.close=function(){this.fs.closeSync(this.fd)};l.prototype.constructor=l;function
k(a){this.fs=require("fs");this.root=a}k.prototype.nm=function(a){return this.root+a};k.prototype.exists=function(a){return this.fs.existsSync(this.nm(a))?1:0};k.prototype.readdir=function(a){return this.fs.readdirSync(this.nm(a))};k.prototype.is_dir=function(a){return this.fs.statSync(this.nm(a)).isDirectory()?1:0};k.prototype.unlink=function(a){var
b=this.fs.existsSync(this.nm(a))?1:0;this.fs.unlinkSync(this.nm(a));return b};k.prototype.open=function(f,c){var
a=require("constants"),b=0;for(var
e
in
c)switch(e){case"rdonly":b|=a.O_RDONLY;break;case"wronly":b|=a.O_WRONLY;break;case"append":b|=a.O_WRONLY|a.O_APPEND;break;case"create":b|=a.O_CREAT;break;case"truncate":b|=a.O_TRUNC;break;case"excl":b|=a.O_EXCL;break;case"binary":b|=a.O_BINARY;break;case"text":b|=a.O_TEXT;break;case"nonblock":b|=a.O_NONBLOCK;break}var
d=this.fs.openSync(this.nm(f),b);return new
l(d)};k.prototype.rename=function(b,a){this.fs.renameSync(this.nm(b),this.nm(a))};k.prototype.constructor=k;var
q=s.match(/[^\/]*\//)[0],u=[];if(typeof
module!=="undefined"&&module.exports&&typeof
require!=="undefined")u.push({path:q,device:new
k(q)});else
u.push({path:q,device:new
h(q)});u.push({path:q+W,device:new
h(q+W)});function
aZ(b){var
f=aD(b),b=f.join(m),e=b+m,c;for(var
d=0;d<u.length;d++){var
a=u[d];if(e.search(a.path)==0&&(!c||c.path.length<a.path.length))c={path:a.path,device:a.device,rest:b.substring(a.path.length,b.length)}}return c}function
ap(e,f){var
b=o[e],d=a(f),c=an(d);b.file.write(b.offset,d,0,c);b.offset+=c;return 0}function
aW(a){var
b=g;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stderr.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.error&&c.error(a)}}function
aX(a){var
b=g;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stdout.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.log&&c.log(a)}}function
w(c,f,e,a){if(d.fds===undefined)d.fds=new
Array();a=a?a:{};var
b={};b.file=e;b.offset=a.append?e.length():0;b.flags=a;b.output=f;d.fds[c]=b;if(!d.fd_last_idx||c>d.fd_last_idx)d.fd_last_idx=c;return c}function
a0(c,b,h){var
a={};while(b){switch(b[1]){case
0:a.rdonly=1;break;case
1:a.wronly=1;break;case
2:a.append=1;break;case
3:a.create=1;break;case
4:a.truncate=1;break;case
5:a.excl=1;break;case
6:a.binary=1;break;case
7:a.text=1;break;case
8:a.nonblock=1;break}b=b[2]}if(a.rdonly&&a.wronly)j(c.toString()+S);if(a.text&&a.binary)j(c.toString()+af);var
e=aZ(c),f=e.device.open(e.rest,a),g=d.fd_last_idx?d.fd_last_idx:0;return w(g+1,ap,f,a)}w(0,ap,new
c(p(0)));w(1,aX,new
c(p(0)));w(2,aW,new
c(p(0)));function
aF(c){var
b=d.fds[c];if(b.flags.wronly)j(Z+c+" is writeonly");var
a={file:b.file,offset:b.offset,fd:c,opened:true,out:false,refill:null};o[a.fd]=a;return a.fd}function
am(e){var
c=d.fds[e];if(c.flags.rdonly)j(Z+e+" is readonly");var
a={file:c.file,offset:c.offset,fd:e,opened:true,out:true,buffer:b};o[a.fd]=a;return a.fd}function
aG(){var
b=0;for(var
a=0;a<o.length;a++)if(o[a]&&o[a].opened&&o[a].out)b=[0,o[a].fd,b];return b}function
aI(a){return a
instanceof
Array?a[0]:a
instanceof
n?252:1e3}function
i(c,b,a){d[c+1]=b;if(a)d[a]=b}var
aH={};function
aC(a){if((a.t&6)!=0)ai(a);return a.c}function
aM(a,b){aH[aC(a)]=b;return 0}var
D=[e,a(_),-7];i(11,[e,a(R),-12],R);i(10,[e,a(L),-11],L);i(9,[e,a(Y),-10],Y);i(8,[e,a($),-9],$);i(7,[e,a(X),-8],X);i(6,D,_);i(5,[e,a(V),-6],V);i(4,[e,a(ab),-5],ab);i(3,[e,a(ad),-4],ad);i(2,[e,a(aa),-3],aa);i(1,[e,a(U),-2],U);i(0,[e,a(K),-1],K);t(0);aF(0);am(1);am(2);t(0);t(0);var
E=[0,0],aw=a("Js.Error"),ay=a("save"),aA=a("para");function
F(a){E[1]=[0,a,E[1]];return 0}var
x=g,G=null,av=x.Array,H=[e,aw,t(0)],y=[0,H,{}],at=undefined,au=true,as=aI(y)===e?y:y[1];aM(a("jsError"),as);(function(a){throw a});F(function(a){return a[1]===H?[0,al(a[2].toString())]:0});F(function(a){return a
instanceof
av?0:[0,al(a.toString())]});var
ax=x.document;function
I(b){var
a=ax.getElementById(b.toString());if(a==G)throw D;return a}t(0);x.HTMLElement===at;var
az=I(ay),aB=I(aA);function
J(a){aB.innerHTML="hello";return au}az.onclick=function(a){if(1-(a==G?1:0)){var
c=J(a);if(1-(c|0))a.preventDefault();return c}var
d=event,b=J(d);if(1-(b|0))d.returnValue=b;return b};function
ar(b){var
a=b;for(;;){if(a){var
c=a[2],d=a[1];try{aE(d)}catch(a){}var
a=c;continue}return 0}}ar(aG(0));return}(function(){return this}()));
